<?php

function ckeditor_widgets_page_attachments(array &$page) {
  $route_match = \Drupal::routeMatch();
  if ($route_match->getRouteName() == 'entity.node.canonical') {
    $node = \Drupal::routeMatch()->getParameter('node');
    $fields = $node->getFields();
    $found = FALSE;
    foreach($fields as $field) {
      $values = $field->getValue();
      foreach($values as $item) {
        foreach($item as $value) {
          if (strpos($value, 'data-accordion')) {
            $found = TRUE;
          }
        }
      }
    }
    if ($found) {
      $page['#attached']['library'][] = 'ckeditor_widgets/ckeditor_widgets_js';
    }
  }
}
